[package]
name = "kvs"
version = "0.0.1"
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "[PoC] Key-Value Store"
categories = ["no-std"]
keywords = ["key-value"]
documentation = "https://docs.rs/kvs"
repository = "https://github.com/dotcypress/kvs"
authors = ["Vitaly Domnikov <oss@vitaly.codes>"]

[dependencies]
byteorder = { version = "1.3.2", default-features = false }
hash32 = "0.1.1"

[features]
default = []
maxCap64 = []
maxCap128 = []
maxCap256 = []
maxCap512 = []
maxCap1024 = []
maxCap2048 = []
maxCap4096 = []
